### ISSUE TITLE
Feedback and a helping hand

### ISSUE THREAD

**Issue by pwab** [TwistedTwigleg/Godot_GSOC_2020_2D_Project#1]
Hey @TwistedTwigleg I'm constantly watching your awesome progress on the IK solvers. I just wanted to give you some feedback (when you need it) and maybe I can help a bit on stuff like test projects or such things.

I've build your latest branch and tried this repositories test scenes and it worked quite good on my machine. Your implementation of FABRIC seems to work way better than mine and I'm eagerly waiting to use it in my projects. I only tested 2D side stuff but if I find the time I'll take a look at the 3D side.

Are you interested in getting some test scene improvements? I don't want to disturb your testground - I only would like to add some test scenes which are more 'visual' (I'm talking about robots and such) and maybe one or two simple scripts for interactions. Would this be of interest for you?

**Comment by TwistedTwigleg** [comment]
Hey @pwab!

Sure, I'd love any feedback you can offer, as well as any improvements to the project. Right now I'm working on a Godette test scene (`Test_07`, ~~only locally for now~~), but I'll be the first to admit my test scenes are not terribly inspiring. If you want to help contribute to the testing scenes, please feel free to make a PR :smile: 

Additionally, if you find any issues or have any feedback on the IK, please let me know, either here or on the Godot engine PR.
