### ISSUE TITLE
Error on Test_10

### ISSUE THREAD

**Issue by pwab** [TwistedTwigleg/Godot_GSOC_2020_2D_Project#3]
As I wanted to build some kinematics with sliders I had to take a look at Test_10 again (with the `GDScript_SpringModificatino2D.gd` script). It still works like before the rebase but now three things bother me:

1. I'm not seeing that the SkeletonModification is set to SkeletonModification2DSpring. It's only set to SkeletonModification2D but still works as expected.
2. When trying to set it to SkeletonModification2DSpring an error appears and nothing else happens. So it can't be set to the GDScript Modification.
3. Number 2 leads to the end that I'm not able to adapt this Modification to a new scene because I'm not able to choose the SpringModification for my Skeleton.

**Here is the error that is displayed:**
` editor\editor_properties.cpp:2564 - Condition "!resp" is true. Breaking.`

**And here is a gif showing the behavior:**
![m4v09ryN4Y](https://user-images.githubusercontent.com/19271185/92155748-2714d280-ee28-11ea-8fc8-ee86858d51e3.gif)

**Comment by TwistedTwigleg** [comment]
Seems to be a Godot engine issue, as all Resources with `@tool` seems to be affected.
I made an issue for it on the Godot repository: https://github.com/godotengine/godot/issues/42134

Closing...
