### ISSUE TITLE
Minimum distance of TwoBoneIK sometimes leads to disappearence of bones

### ISSUE THREAD

**Issue by pwab** [TwistedTwigleg/Godot_GSOC_2020_2D_Project#4]
I'm not yet sure if the title is correct but I encountered a strange thing where the TwoBoneIK somehow hides the bones if no pose solution can be found and the minimum distance is set to default (which is 6). It looks like that:

![VdyEdXLY4Y](https://user-images.githubusercontent.com/19271185/93027035-af565d00-f60a-11ea-9eb5-689a2aa5d422.gif)

Here you can see two TwoBoneIKs trying to reach the target. When getting near the basis the bones disappear (in game and in editor). This can only be reverted by deactivating the SkeletonModification (`enabled = off`).

Has this something to do with the `minimum_distance`? Because if I set it to for example 100 the TwoBoneIK is working fine and stops the chain at the distance of 100.

---

Apart from that: Would it be possible to add a `maximum_distance` feature working like the minimum one?

**Comment by TwistedTwigleg** [comment]
Just copying my reply from #2 over here, for anyone who hasn't read it yet:

> ... is a bug with the TwoBoneIK solver. I have a hunch that it occurs when the two bones in the solver are folded into each other completely. I will need to debug this and see if I can fix it.

Also, it probably is related to the minimum distance. When the minimum distance is too small, the bones can fold into themselves and I believe that is causing the issue. One potential solution would be setting the minimum distance to a minimum value based on the lengths of the bones, but ideally I should find a fix that makes it where the issue does not occur regardless of the minimum distance.

> Apart from that: Would it be possible to add a maximum_distance feature working like the minimum one?

Sure, it shouldn't be too difficult to add. I'll add a maximum distance property when I'm working on the TwoBoneIK fix!

**Comment by pwab** [comment]
> One potential solution would be setting the minimum distance to a minimum value based on the lengths of the bones [...]

Well that sounds reasonable. Because there are no solutions below the `(bone_length_1 - bone_length_2)`-distance. So setting the min value of the minimum_distance to the lowest possible (always updated when the bone lengths have changed) should do the job.
But I don't have taken a look into the code behind so I'm just guessing.

Only one point to add. The solution should be tested with those three configurations:

- `bone_length_1 > bone_length_2`
- `bone_length_1 < bone_length_2`
- `bone_length_1 == bone_length_2`

I could create a test_scene for that.

>  I'll add a maximum distance property when I'm working on the TwoBoneIK fix!

👌😃

**Comment by pwab** [comment]
I was curious how the TwoBoneIK behaves in 3D. At least in the test scene nothing disappears when the bones overlap:

![Test_07_TwoBoneIk](https://user-images.githubusercontent.com/19271185/93259404-178a7780-f7a0-11ea-86e9-c4e83ed4c46b.gif)

**Comment by TwistedTwigleg** [comment]
Interesting. I wonder if the reason is that in 3D it has the benefit of having the pole node to help define the bend axis. That might help give a clue as to why the TwoBoneIK in 2D has the disappearing issue... Something to look into at any rate. Thanks for letting me know! 👍

**Comment by pwab** [comment]
> I wonder if the reason is that in 3D it has the benefit of having the pole node to help define the bend axis.

At least it adds lots of stability to the result of the pose calculation:

![d5ATEg9ZQ6](https://user-images.githubusercontent.com/19271185/93380818-07d26800-f860-11ea-8bae-e21ed2e1f13a.gif)

(Just one note: I changed to auto calculated bone lengths - not that this has changed anything as far as I'm aware of.)

**Comment by TwistedTwigleg** [comment]
I just recently pushed a commit that should fix the issue. The issue turned out to be that the `acos` function was sometimes returning `NaN` when the joints were too close together. I added a condition to fix this and now it should work regardless of the minimum distance.

**Comment by pwab** [comment]
Issue seems fixed. I tried with different samples and nothing disappeared. 👍 

---

Only thing I've noticed while testing is a lack of some kind of visible border (for debugging) when using the minimum or maximum distance. Something like the circle that is shown when using limited angles which should have the radius of the used parameters.

**Comment by TwistedTwigleg** [comment]
I’ll see about adding a line or something for debugging to show the minimum and maximum distances when I rebase with master.

Or maybe a circle or pair of circles? Hmm, will have to experiment!

**Comment by pwab** [comment]
A pair of circles seem like a good fit. But it should be distinct from the angle constraints circle. Not easy to get the visuals right here.

Maybe also an Editor switch could be introduced for switching the visibility of the lines on and off.
